Add missing `id` to request data
fazland/fatture-in-cloud-sdk pull request #7
Opened 2018-12-24 15:06 UTC by dlondero

`id` is mandatory but gets removed from array_diff_assoc because it has the same value (of course) in `$fields` and in `$this->originalData`. Adding it directly from the instance. 

@alekitto please check

2018-12-24 17:22 UTC, alekitto commented
Correct. But probably the `$id` property should be private or protected, with `__get` accessor to protect it from unintended modifications.

2018-12-24 18:55 UTC, dlondero commented
@alekitto makes sense. Please verify.

2018-12-26 20:34 UTC, alekitto requested changes
Some changes are needed before merging this.

2018-12-26 20:34 UTC, alekitto commented on lib/Model/Subject/Subject.php
> +                return $this->id ? $this->id : null;
`return $this->id` should be sufficient

2018-12-26 20:34 UTC, alekitto commented on lib/Model/Subject/Subject.php
> +                break;
This should be removed. The `$id` property should only be set by class methods and not modified by external process.

2018-12-26 20:34 UTC, alekitto commented on lib/Model/Subject/Subject.php
> +        $this->__set('id', $data['id'] ?? null);
`$id` can be set directly, no modification is needed.

2018-12-26 21:09 UTC, dlondero commented
@alekitto there you go :)

2018-12-26 21:40 UTC, alekitto approved these changes

2018-12-26 21:40 UTC, merged

2018-12-26 22:36 UTC, dlondero commented
@alekitto there's an issue here https://github.com/fazland/fatture-in-cloud-sdk/blob/master/lib/Model/Document/Document.php#L575-L581 where `__set` is needed. Other solution is to call `Customer::fromArray` or `Supplier::fromArray` which would be ok, preparing the params' array to pass (maybe clone `$body` and replace `id` with `id_cliente`/`id_fornitore` value ). Wdyt?

2018-12-26 22:46 UTC, alekitto commented
I fixed it just now, right before seeing your comment 😄

2018-12-26 22:49 UTC, dlondero commented
Cool!